// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://plcactasqlbihqbptjkv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBsY2FjdGFzcWxiaWhxYnB0amt2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4MTc1OTIsImV4cCI6MjA3MTM5MzU5Mn0.88s9YVlURh_7vnZBYxpTwsLIEujx6_ej-Ge3uel88Jg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});